import Head from 'next/head'
import Shortener from '../components/Forms/Shortener'
import styles from '../styles/Home.module.css'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          URL Shortener
        </h1>

        <div className={styles.grid}>
          <Shortener />
        </div>

      </main>
    </div>
  )
}
