import Head from 'next/head'
import classnames from 'classnames'

// import useAuth from '../hooks/useAuth'
// import { firebaseAuth } from '../firebase/Auth'
import styles from '../styles/Home.module.css'
import cardStyle from '../styles/Card.module.css'

import Icon from '@mdi/react'
import { mdiLinkVariant } from '@mdi/js'
import AuthButton from '../components/Common/AuthButton'

export default function Home() {
  // const { user, loading } = useAuth()

  // const handleClick = ({ target }) => {
  //   firebaseAuth(target.name)
  //     .then((data) => {
  //       setUser(data.user)
  //       setIsAuth(true)
  //     })
  //     .catch((err) => console.log(err))
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={cardStyle.wrap}>
          <div className={classnames(cardStyle.cardHeader, cardStyle.gradient)}>
            <Icon path={mdiLinkVariant} size={2} color="#fff" />
          </div>
          <div className={cardStyle.cardContent}>
            <h1 className={cardStyle.cardTitle}>URL Shortener</h1>
            <p className={cardStyle.cardText}>
              Simple and effective free url shortener.
            </p>
            <AuthButton text="youtube" />
          </div>
        </div>
      </main>
    </div>
  )
}
